config/routes.rb
Rails.application.routes.draw do
  root to: "homes#home"
  get 'homes/home'
  get 'rooms/new'
  get 'reservations/index'
  get 'users/account'

  get '/account',to:'users#account'
  get '/profile',to:'users#profile'

  devise_for :users,controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }

  resources :users
  get 'rooms/search',to:'rooms#search'
  get 'rooms/posts',to:'rooms#posts'
  resources :rooms
  resources :reservations

end

app/models/reservation.rb
class Reservation < ApplicationRecord

  belongs_to :user
  belongs_to :room

  validates :person, presence:true
  validate :start_date_check
  validate :start_end_check

  def start_date_check
    errors.add(:start_date,"に過去の日付は指定できません") if start_date.nil? || start_date < Date.today
  end
  def start_end_check
    errors.add(:end_date,"は開始日より後の日付を指定してください") if end_date.nil? || start_date > end_date
  end

end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
    def index
      @user = current_user
      @reservation = Reservation.where(user_id: @user.id)
    end

    def new
      @reservation = Reservation.new(params_reservation)
      if @reservation.valid?
        @room = Room.find(@reservation.room_id)
        @days = (@reservation.end_date - @reservation.start_date).to_i
        @price = @room.price*@days*@reservation.person
      else
        @room = Room.find(@reservation.room_id)
        @user = User.find(@room.user_id)
        @reserv = current_user
        if user_signed_in?
          @user_check = User.exists?(id: @reserv.id,introduction: nil)
        end
        render template:"rooms/show"
      end
    end

    def create
      @reservation = Reservation.new(params_reservation)
      if @reservation.save
        flash[:notice]="ルームの予約が完了しました"
        redirect_to reservation_path(@reservation.id)
      else
        flash[:notice]="ルームの予約に失敗しました"
        render "new"
      end

    end

    def show
      @reservation = Reservation.find(params[:id])
      @room = Room.find(@reservation.room_id)
    end

    def edit
    end

    def update
    end

    def destroy
    end

    private
    def params_reservation
      params.require(:reservation).permit(:user_id,:room_id,:start_date,:end_date,:person,:total_price)
    end

  end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/views/reservations/index.html.erb
<div class="container-fiuld reservations">
  <h4 class="pb-4">予約済みルーム一覧</h4>
  <table>

    <thead>
      <tr class="text-center">
        <th>ルーム画像</th>
        <th>ルーム名</th>
        <th>ルーム紹介</th>
        <th>合計料金</th>
        <th>開始日</th>
        <th>終了日</th>
        <th>予約確定日時</th>
      </tr>
    </thead>

    <tbody>
      <% @reservation.each do |r| %>
        <tr>
          <td>
          <%= link_to room_path(r.room.id) do %>
            <%= image_tag r.room.picture,size:"240x140" %>
          <% end %>
          </td>

          <td>
          <%= link_to r.room.name, room_path(r.room.id) ,class:"reservation-room-name" %>
          </td>
          <td>
            <%= r.room.information %>
          </td>
          <td>
            <%= r.start_date %>
          </td>
          <td>
            <%= r.end_date %>
          </td>
          <td>
            <%= r.total_price %>
          </td>
          <td>
            <%= r.updated_at%>
          </td>
        </tr>

      <% end %>
    </tbody>
  </table>
</div>

app/views/reservations/new.html.erb
<div class="container reservation-new">
  <div class="row">
    <div class="col-6 offset-3">
      <div class="reservation-new-nav">
        <h4 class="reservation-new-title">予約確認画面</h4>
        <h5 class="price-icon"><%= @room.price %> /円</h5>
        <div class="reservations-new-date-select">

          <%=form_with model:@reservation do |r| %>
            <div>開始日</div>
            <%= r.date_field :start_date ,:value =>@reservation.start_date,class:"form-control mb-4 w-100" %>
            <div>終了日</div>
            <%= r.date_field :end_date ,:value =>@reservation.end_date,class:"form-control mb-4 w-100" %>
            <div>使用日数：<%= @days %>日　</div>
            <div>人数</div>
            <%= r.text_field :person ,:value =>@reservation.person,class:"form-control mb-4 w-100" %>
            <div>合計金額</div>
            <%= r.text_field :total_price ,:value =>@price,class:"form-control mb-4 w-100" %>
            <%= r.hidden_field :room_id, :value =>@reservation.room_id %>
            <%= r.hidden_field :user_id, :value =>@reservation.user_id %>
            <%= r.submit "予約を確定する",class:"btn btn-primary w-100 mb-2" %>
            <%= link_to "ルーム詳細に戻る",room_path(@room.id) ,class:"btn btn-secondary w-100"%>
          <% end %>

        </div>
      </div>
    </div>
  </div>
</div>

app/views/reservations/show.html.erb
<div class="container-fiuld user">
  <div class="row">
    <div class="col-12 reservation-view">
      <div class="reservation-view-box">
        <div class="reservation-box">
          <div class="row reservation-content">
            <label class="col-3">予約した部屋</label>
            <div class="col-9">
              <%=link_to @room.name,room_path(@room.id),class:"room-link" %>
            </div>
          </div>
          <div class="row reservation-content">
            <label class="col-3">開始日</label>
            <div class="col-9">
              <%= @reservation.start_date %>
            </div>
          </div>
          <div class="row reservation-content">
            <label class="col-3">終了日</label>
            <div class="col-9">
              <%= @reservation.end_date %>
            </div>
          </div>
          <div class="row reservation-content">
            <label class="col-3">価格</label>
            <div class="col-9">
              <%= @reservation.total_price %>円
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>