config/routes.rb
Rails.application.routes.draw do
  root to: "homes#home"
  get 'homes/home'
  get 'rooms/new'
  get 'reservations/index'
  get 'users/account'

  get '/account',to:'users#account'
  get '/profile',to:'users#profile'

  devise_for :users,controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }

  resources :users
  get 'rooms/search',to:'rooms#search'
  get 'rooms/posts',to:'rooms#posts'
  resources :rooms
  resources :reservations

end

app/models/room.rb
class Room < ApplicationRecord

  belongs_to :user
  has_one_attached :picture
  has_many :reservations

  validates :name,presence:true
  validates :information,presence:true
  validates :price,presence:true,numericality:true
  validates :address,presence:true
  validates :picture,presence:true

end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController

    def index
    end

    def new
      @user =current_user
      @user_check = User.exists?(id: @user.id,introduction: nil)
      @room = Room.new
    end

    def create
      @room = Room.new(rooms_params)
      @room.user_id = current_user.id
      if @room.save
        flash[:notice] = "ルームの新規登録が完了しました"
        redirect_to room_path(@room.id)
      else
        @user =current_user
        @user_check = User.exists?(id: @user.id,introduction: "")
        render "new"
      end
    end

    def posts
      @user = current_user
      @room = Room.where(user_id:@user.id)
    end

    def show
      @room = Room.find(params[:id])
      @user = User.find(@room.user_id)
      @reserv = current_user
      @reservation =Reservation.new
      if user_signed_in?
        @user_check = User.exists?(id: @reserv.id,introduction: nil)
      end
    end

    def search
      if params[:area] == nil && params[:keyword] == nil
        @room = Room.all
        @cnt = Room.all.count
      elsif params[:area] == "" && params[:keyword] == ""
        @room = Room.all
        @cnt = Room.all.count
      elsif params[:area]
        @room = Room.where("address LIKE?",'%'+params[:area]+'%')
        @cnt = Room.where("address LIKE?",'%'+params[:area]+'%').count
      elsif  params[:keyword]
        @room = Room.where("name LIKE?",'%'+params[:keyword]+'%').or(Room.where("address LIKE?",'%'+params[:keyword]+'%')).or(Room.where("information LIKE?",'%'+params[:keyword]+'%')) .or(Room.where("price LIKE?",'%'+params[:keyword]+'%'))
        @cnt = Room.where("name LIKE?",'%'+params[:keyword]+'%').or(Room.where("address LIKE?",'%'+params[:keyword]+'%')).or(Room.where("information LIKE?",'%'+params[:keyword]+'%')) .or(Room.where("price LIKE?",'%'+params[:keyword]+'%')) .count
      else
      end
    end

    def edit
    end

    def update
    end


    def rooms_params
      params.require(:room).permit(:user_id,:name,:information,:price,:address,:picture)
    end
  end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/new.html.erb
<%if @user_check == false %>
  <div class="container room-show-container">
    <div class="row">
      <div class="col-2">
        <%=render "shared/roombar" %>
      </div>

      <div class="col-10 room-view">
        <div class="room-new-box">
          <%= form_with model:@room ,url:rooms_path,local:true,method: :post do |r| %>
            <div class="room-new-field mb-3 ">
              <h3>ルーム情報登録</h3>
            </div>
            <div class="room-new-field mb-5 ">
              <%=render "shared/error",obj:@room %>
            </div>
            <div class="room-new-field mb-3 ">
              <div class="row">
                <div class="col-3">
                  <label>ルーム名</label>
                  <span class="badge badge-danger">必須</span>
                </div>
                <div class="col-9">
                  <%= r.text_field :name,class:"w-100" %>
                </div>
              </div>
            </div>

            <div class="room-new-field mb-3 ">
              <div class="row">
                <div class="col-3">
                <label>ルーム紹介</label>
                  <span class="badge badge-danger">必須</span>
                </div>
                <div class="col-9">
                  <%= r.text_area :information,class:"w-100" %>
                </div>
              </div>
            </div>

            <div class="room-new-field mb-3 ">
              <div class="row">
                <div class="col-3">
                <label>料金</label>
                  <span class="badge badge-danger">必須</span>
                </div>
                <div class="col-9">
                  <%= r.text_field :price,type:"number",class:"w-100" %>
                </div>
              </div>
            </div>

            <div class="room-new-field mb-3 ">
              <div class="row">
                <div class="col-3">
                <label>住所</label>
                  <span class="badge badge-danger">必須</span>
                </div>
                <div class="col-9">
                  <%= r.text_field :address,class:"w-100" %>
                </div>
              </div>
            </div>

            <div class="room-new-field mb-3 ">
              <div class="row">
                <div class="col-3">
                <label>ルーム画像</label>
                  <span class="badge badge-danger">必須</span>
                </div>
                <div class="col-9">
                  <%= r.file_field :picture %>
                </div>
              </div>
            </div>

            <div class="col-3 p-0">
              <%= r.submit "登録", class:"p-2 m-1 btn-outline-primary text-white bg-primary col-12 rounded" %>
            </div>
        <% end %>
      </div>
    </div>
  </div>

<%else%>
  <div class="container room-show-container room-profile-access">
    <h3>ルーム登録を行うには、プロフィールの編集を行ってください</h3>
    <%= link_to "プロフィール編集画面へ",profile_path ,class:"btn btn-primary"%>
  </div>

<%end%>

app/views/rooms/posts.html.erb
<div class="room-posts">
  <h4 class="pd-4">登録済みルーム一覧</h4>
  <table class="posts-table">
  <thead>
    <tr>
      <th>ルーム画像</th>
      <th>ルーム名</th>
      <th>ルーム紹介</th>
      <th>料金</th>
      <th>作成日</th>
    </tr>
  </thead>
  <tbody>
    <% @room.each do |room| %>
      <tr>
        <td>
          <%= image_tag room.picture,:size => "200x200"%>
        </td>
        <td class="posts-name"><%=link_to room.name,room_path(room.id) %></td>
        <td><%= room.information %></td>
        <td>¥<%= room.price %></td>
        <td><%= room.created_at %></td>
      </tr>
    <% end %>
  </tbody>
  </table>
</div>

app/views/rooms/search.html.erb
<div class="room">
  <div class="row">
    <% if @room.present? %>
      <h3 class="col-12 search-number">検索結果 <%= @cnt %>件です</h3>
      <% @room.each do |room| %>
        <div class="col-3">
          <div class="room-search-frame">
            <%= link_to room_path(room.id),class:"room-link" do %>
              <div class="search-profile-image">
                <%= image_tag room.picture ,width:"100%",height:"100%",class:"pt-3" %>
              </div>
              <div class="room-search-profile">
                <div class="search-profile-name"><%= room.name %></div>
                <div class="search-profile-address"><%= room.address %></div>
                <div class="search-profile-price">¥<%= room.price %></div>
              </div>
            <% end %>
          </div>
        </div>
      <% end %>
    <% else %>
      <h3>検索結果はありませんでした</h3>
    <% end %>
  </div>
</div>

app/views/rooms/show.html.erb
<div class="clearfix">
  <%= render "shared/error_form",{ object:@reservation, url: new_reservation_path } %>
</div>
<div class="container room-show">
  <div class="row">
    <div class="col-8">
      <%= image_tag @room.picture ,class:"w-100 room-show-picture" %>
      <div class="room-show-detile  mt-5">
        <div class="room-show-detile-icon">
          <%= image_tag @user.image ,style: "border-radius: 50%",:size => "70x70" %>
        </div>
        <div class="room-show-profile ml-4">
          <p class="room-show-profile-name"><%= @room.name %></p>
          <p class="room-show-profile-adress"><%= @room.address %></p>
        </div>
      </div>
      <p class="mt-3 room-show-profile-intro"><%= @room.information %></p>

    </div>
    <div class="col-4">
      <div class="room-show-nav">
        <h5 class="price-icon"><%= @room.price %> /円</h5>
        <div class="room-show-date-select">
          <%=form_with model:@reservation ,url: new_reservation_path,local:true,method: :get do |r| %>
            <label>開始日</label>
            <%= r.date_field :start_date ,class:"room-show-form mb-4 w-100" %>
            <label>終了日</label>
            <%= r.date_field :end_date ,class:"room-show-form mb-4 w-100" %>
            <label>人数</label>
            <%= r.text_field :person, type:"number" ,class:"room-show-form mb-4 w-100" %>

            <% if @user_check == true %>
              <%= link_to "プロフィールを編集する", profile_path,class:"btn btn-secondary w-100" %>
            <% elsif @user_check == false  %>
              <%= r.hidden_field :user_id ,:value =>@reserv.id ,class:"room-show-form mb-4" %>
              <%= r.hidden_field :room_id ,:value =>@room.id ,class:"room-show-form mb-4" %>
              <%= submit_tag "予約する" ,class:"btn btn-primary w-100" %>
            <% else %>
              <%= link_to "ログインする", "/users/sign_in",class:"btn btn-secondary w-100" %>
            <% end %>
          <% end %>
        </div>
        </div>
    </div>
  </div>
</div>