config/routes.rb
Rails.application.routes.draw do
  root to: "homes#home"
  get 'homes/home'
  get 'rooms/new'
  get 'reservations/index'
  get 'users/account'

  get '/account',to:'users#account'
  get '/profile',to:'users#profile'

  devise_for :users,controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }

  resources :users
  get 'rooms/search',to:'rooms#search'
  get 'rooms/posts',to:'rooms#posts'
  resources :rooms
  resources :reservations

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rails課題2</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

  </head>

  <body>
    <header>
        <div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 header-container shadow-sm">

          <div class="header-left-container">

              <%= link_to root_path do %>
              <%= link_to image_tag("logo.png", height:'50px', class:"my-0 mr-md-auto font-weight-normal",id:"home-logo", alt:"ロゴ"), root_path %>
              <% end %>
                <div class="header-search-container mt-3">
                      <div class="header-search-box">
                        <%= form_with url: rooms_search_path,method: :get,local: true do |f| %>
                          <%= f.text_field :area ,placeholder:"エリア検索",class:"header-search-input"%>
                          <% submit_tag %>
                        <% end %>
                        <i class="fas fa-map-marker-alt"></i>
                      </div>

                      <div class="header-search-box">
                        <%= form_with url: rooms_search_path,method: :get,local: true do |f| %>
                          <%= f.text_field :keyword ,placeholder:"キーワード検索",class:"header-search-input"%>
                          <% submit_tag %>
                        <% end %>
                        <i class="fas fa-search "></i>
                      </div>
                  </div>
            </div>


            <div class="header-right-container">
              <% if user_signed_in? %>
                <div class="p-2 m-1 text-white header-user-name"><%= current_user.name %></div>

                  <div class="dropdown">
                      <button type="button" id="dropdownMenuButton" data-bs-toggle="dropdown" aria-expanded="false"><!---CSS icon foto--->
                      <div class="user_header_image nav-item p-2 m-1">
                            <% if current_user.image.attached? %>
                              <%= image_tag current_user.image ,style: "border-radius: 50%",:size => "65x65" %>
                            <%else%>
                              <%= image_tag "upper_body-2.png",style: "border-radius: 50%",:size => "65x65"%>
                            <%end%>
                      </div>
                      </button>

                      <ul class="p-2 mb-0 header-nav-menu dropdown-menu" aria-labelledby="dropdownMenuButton" >
                        <li class="mb-1"><%=link_to "ルーム登録",new_room_path,class: "nav_link dropdown-item",:style=>"color:black;"%></li>
                        <li class="mb-1"><%=link_to "予約済みルーム一覧",reservations_path,class: "nav_link dropdown-item",:style=>"color:black;" %></li>
                        <li class="mb-1"><%=link_to "登録済みルーム一覧",rooms_posts_path,class: "nav_link dropdown-item",:style=>"color:black;"%></li>
                        <li class="mb-1"><%=link_to "設定",account_path,class: "nav_link dropdown-item",:style=>"color:black;"%></li>
                        <li class="mb-1"><%=link_to "ログアウト",destroy_user_session_path,method: :delete,class: "nav_link dropdown-item",:style=>"color:black;"%></li>
                      </ul>
                    </div>






                  <% else %>
                    <%= link_to"ログイン","/users/sign_in",class:"home-link-user p-2 m-1 btn btn-outline-primary text-white bg-primary"%>
                    <%= link_to"新規登録","/users/sign_up",class:"home-link-user p-2 m-1 btn btn-outline-info text-white bg-info"%>
                <% end %>

            </div>
      </div>



            <script>
              $('.user_headnav').hide();
              $('.user_header_image').on('click',function(){
                $('.user_headnav').slideToggle();
              })
            </script>
    </header>
              <main>
                <div class="clearfix">
                  <%= notice %>
                  <%= alert %>
                </div>
                <%= yield %>
              </main>


   <footer>
     <p>©︎ 2020 POTEPAN.INC.</p>
   </footer>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
  </body>
</html>